server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    # Config Server
    config:
      uri: http://localhost:8888

    gateway:
      discovery:
        locator:
          enabled: true # find Eureka services

      routes:
        - id: zone-service
          uri: lb://ZONE-SERVICE # 'lb://'Load Balancer
          predicates:
            - Path=/api/zones/**

# Eureka Client settings
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true